require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HousingsController do

  # This should return the minimal set of attributes required to create a valid
  # Housing. As you add validations to Housing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "available" => "2013-12-05" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HousingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all housings as @housings" do
      housing = Housing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:housings).should eq([housing])
    end
  end

  describe "GET show" do
    it "assigns the requested housing as @housing" do
      housing = Housing.create! valid_attributes
      get :show, {:id => housing.to_param}, valid_session
      assigns(:housing).should eq(housing)
    end
  end

  describe "GET new" do
    it "assigns a new housing as @housing" do
      get :new, {}, valid_session
      assigns(:housing).should be_a_new(Housing)
    end
  end

  describe "GET edit" do
    it "assigns the requested housing as @housing" do
      housing = Housing.create! valid_attributes
      get :edit, {:id => housing.to_param}, valid_session
      assigns(:housing).should eq(housing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Housing" do
        expect {
          post :create, {:housing => valid_attributes}, valid_session
        }.to change(Housing, :count).by(1)
      end

      it "assigns a newly created housing as @housing" do
        post :create, {:housing => valid_attributes}, valid_session
        assigns(:housing).should be_a(Housing)
        assigns(:housing).should be_persisted
      end

      it "redirects to the created housing" do
        post :create, {:housing => valid_attributes}, valid_session
        response.should redirect_to(Housing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved housing as @housing" do
        # Trigger the behavior that occurs when invalid params are submitted
        Housing.any_instance.stub(:save).and_return(false)
        post :create, {:housing => { "available" => "invalid value" }}, valid_session
        assigns(:housing).should be_a_new(Housing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Housing.any_instance.stub(:save).and_return(false)
        post :create, {:housing => { "available" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested housing" do
        housing = Housing.create! valid_attributes
        # Assuming there are no other housings in the database, this
        # specifies that the Housing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Housing.any_instance.should_receive(:update).with({ "available" => "2013-12-05" })
        put :update, {:id => housing.to_param, :housing => { "available" => "2013-12-05" }}, valid_session
      end

      it "assigns the requested housing as @housing" do
        housing = Housing.create! valid_attributes
        put :update, {:id => housing.to_param, :housing => valid_attributes}, valid_session
        assigns(:housing).should eq(housing)
      end

      it "redirects to the housing" do
        housing = Housing.create! valid_attributes
        put :update, {:id => housing.to_param, :housing => valid_attributes}, valid_session
        response.should redirect_to(housing)
      end
    end

    describe "with invalid params" do
      it "assigns the housing as @housing" do
        housing = Housing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Housing.any_instance.stub(:save).and_return(false)
        put :update, {:id => housing.to_param, :housing => { "available" => "invalid value" }}, valid_session
        assigns(:housing).should eq(housing)
      end

      it "re-renders the 'edit' template" do
        housing = Housing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Housing.any_instance.stub(:save).and_return(false)
        put :update, {:id => housing.to_param, :housing => { "available" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested housing" do
      housing = Housing.create! valid_attributes
      expect {
        delete :destroy, {:id => housing.to_param}, valid_session
      }.to change(Housing, :count).by(-1)
    end

    it "redirects to the housings list" do
      housing = Housing.create! valid_attributes
      delete :destroy, {:id => housing.to_param}, valid_session
      response.should redirect_to(housings_url)
    end
  end

end
